name: torch
channels:
  - pytorch
  - conda-forge
  - numba/label/dev
  - anaconda
  - defaults
dependencies:
  - astroid=2.3.3=py36_0
  - blas=1.0=mkl
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - cffi=1.13.2=py36h7a1dbc1_0
  - cloudpickle=1.2.2=py_0
  - colorama=0.4.1=py36_0
  - cudatoolkit=9.2=0
  - cycler=0.10.0=py36h009560c_0
  - cytoolz=0.10.1=py36he774522_0
  - dask-core=2.8.1=py_0
  - decorator=4.4.1=py_0
  - freetype=2.9.1=ha9979f8_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14hc45fdbb_0
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=245
  - isort=4.3.21=py36_0
  - joblib=0.14.0=py_0
  - jpeg=9c=hfa6e2cd_1001
  - kiwisolver=1.1.0=py36ha925a31_0
  - lazy-object-proxy=1.4.3=py36he774522_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.0=default_hf44288c_4
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_0
  - libwebp=1.0.2=hfa6e2cd_4
  - matplotlib=3.1.1=py36hc8f65d3_0
  - mccabe=0.6.1=py36_1
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hb782905_0
  - mkl_fft=1.0.15=py36h14836fe_0
  - mkl_random=1.1.0=py36h675688f_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py36h74a9793_0
  - numpy=1.17.4=py36h4320e6b_0
  - numpy-base=1.17.4=py36hc3f5095_0
  - olefile=0.46=py36_0
  - opencv=3.3.1=py36h20b85fd_1
  - openssl=1.1.1=he774522_0
  - pillow=6.2.1=py36hdc69c19_0
  - pip=19.3.1=py36_0
  - pycparser=2.19=py36_0
  - pylint=2.4.4=py36_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py36ha878b3d_0
  - python=3.6.9=h5500b2f_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.6_cuda92_cudnn7_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36he774522_0
  - qt=5.9.7=vc14h73c81de_0
  - scikit-image=0.15.0=py36ha925a31_0
  - scikit-learn=0.21.3=py36h6288b17_0
  - scipy=1.3.1=py36h29ff71c_0
  - setuptools=42.0.1=py36_0
  - sip=4.19.13=py36ha925a31_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=he774522_0
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.2=py36_cu92
  - tornado=6.0.3=py36he774522_0
  - typed-ast=1.4.0=py36he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.6=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - wrapt=1.11.2=py36he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
prefix: C:\Users\muzaf\Anaconda3\envs\torch

